cps2/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

cps2/todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path(route, view, name)
app_name = 'todolist'
urlpatterns = [
    # /todolist route
    path('', views.index, name='index'),
    path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    path('register', views.register, name='register'),
    path('update_profile/<int:user_id>', views.update_profile, name='update_profile'),
   
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
   
    path('add_task', views.add_task, name='add_task'),
    path('edit/<int:todoitem_id>', views.update_task, name='update_task'),
    path('delete/<int:todoitem_id>', views.delete_task, name='delete_task'),
    
    path('add_event', views.add_event, name='add_event'),
    path('events/<int:event_id>', views.todoevent, name='viewevent'),
]

cps2/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} To Do App {% endblock %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	{% include "navbar.html" %}
	{% block content %}
	{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

cps2/templates/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">To Do List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
        </li>
        <li class="nav-item" id="add_nav">
          <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
        </li>
        <li class="nav-item" id="add_event">
          <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
        </li>
        {% if request.user.id is not None %}
        <li class="nav-item" id="update_prof">
          <a class="nav-link" href="{% url 'todolist:update_profile' request.user.id %}">Update Profile</a>
        </li>
        {% endif %}
        <li class="nav-item" id="login_nav">
          <a class="nav-link" href="login">Login</a>
        </li>
        <li class="nav-item" id="regi_nav">
          <a class="nav-link" href="register">Register</a>
        </li>
        <li class="nav-item" id="logout_nav">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>