cps2/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

cps2/todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path(route, view, name)
app_name = 'todolist'
urlpatterns = [
    # /todolist route
    path('', views.index, name='index'),
    path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    path('register', views.register, name='register'),
    path('update_profile/<int:user_id>', views.update_profile, name='update_profile'),
   
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
   
    path('add_task', views.add_task, name='add_task'),
    path('edit/<int:todoitem_id>', views.update_task, name='update_task'),
    path('delete/<int:todoitem_id>', views.delete_task, name='delete_task'),
    
    path('add_event', views.add_event, name='add_event'),
    path('events/<int:event_id>', views.todoevent, name='viewevent'),
]

cps2/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class Event(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	event_date = models.DateTimeField('event date')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

cps2/todolist/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User

class LoginForm(forms.Form):
	username = forms.CharField(label="Username", max_length=20)
	password = forms.CharField(label="Password", max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class RegisterForm(forms.Form):
	username = forms.CharField(label="Username", max_length=20)
	first_name = forms.CharField(label="First Name", max_length=20)
	last_name = forms.CharField(label="Last Name", max_length=20)
	email = forms.EmailField(label="Email", max_length=50)
	password = forms.CharField(label="Password", max_length=20)
	con_password = forms.CharField(label="Confirm Password", max_length=20)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="Status", max_length=50)

class EventForm(forms.Form):
	event_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class UpdateUserForm(forms.ModelForm):
	first_name = forms.CharField(label="First Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'password']

cps2/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required

# Local Imports
from .models import ToDoItem, Event
from .forms import LoginForm, AddTaskForm, RegisterForm, UpdateTaskForm, EventForm, UpdateUserForm

def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	event_list = Event.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		'event_list': event_list,
		'user': request.user
	}
	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def todoevent(request, event_id):
	todoevent = get_object_or_404(Event, pk=event_id)
	return render(request, "todolist/view_event.html", model_to_dict(todoevent))

def register(request):
	context = {}

	if request.method == 'POST':
		form = RegisterForm(request.POST)

		if form.is_valid() == False:
			form = RegisterForm()
		else:
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			con_password = form.cleaned_data['con_password']
			hash_pass = make_password(password)
			user = authenticate(username=username, first_name=first_name, last_name=last_name, email=email, password=hash_pass)
			context = {
				"username": username,
				"first_name": first_name,
				"last_name": last_name,
				"email": email,
				"password": hash_pass,
			}
			
			duplicates = User.objects.filter(username=username)	

			if password == con_password:
				if not duplicates:
					User.objects.create(username=username, first_name=first_name, last_name=last_name, email=email, password=hash_pass)
					return redirect("todolist:login")
				else:	
					context = {
						"error": True
					}
			else:
				context = {
					"match": True
				}
	return render(request, "todolist/register.html", context)

def login_view(request):
	context = {}

	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()
		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}
	return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			duplicates = ToDoItem.objects.filter(task_name=task_name)	

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def add_event(request):
	context = {}

	if request.method == 'POST':
		form = EventForm(request.POST)

		if form.is_valid() == False:
			form = EventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			duplicates = Event.objects.filter(event_name=event_name)

			if not duplicates:
				Event.objects.create(event_name=event_name, description=description, event_date=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)

def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status,
	}

	if request.method == "POST":
		form = UpdateTaskForm(request.POST)
		if form.is_valid() == False:
			form = UpdateTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

@login_required
def update_profile(request, user_id):
	user = get_object_or_404(User, id=user_id)
	if request.method == 'POST':
		form = UpdateUserForm(request.POST, instance=user)
		if form.is_valid():
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password']
			
			if password != '':
				user.password = make_password(form.cleaned_data['password'])
			else:
				user.password = request.user.password

			form.save()
			return redirect('todolist:index')
	else:
		form = UpdateUserForm(instance=user)

	context = {
		"user_id": user_id,
		"user": user,
		"form": form
	}

	return render(request, "todolist/update_profile.html", context)

cps2/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %} Add Event {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add an Event</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate event found</p>
			{% endif %}
			<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="event_name">Event Name: </label>
					<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" required></textarea>
				</div>
				<div class="text-center d-grid gap-1">
					<input class="btn btn-success" type="submit" value="Add Event">
				</div>
			</form>
			<script type="text/javascript">
				login_nav = document.getElementById('login_nav');
				regi_nav = document.getElementById('regi_nav');
				
				login_nav.style.display = 'none';
				regi_nav.style.display = 'none';
			</script>
		</div>
	</div>
</div>

{% endblock %}

cps2/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %} Add Task {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add a Task</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate task found</p>
			{% endif %}
			<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" required></textarea>
				</div>
				<div class="text-center d-grid gap-1">
					<input class="btn btn-success" type="submit" value="Add Task">
				</div>
			</form>
			<script type="text/javascript">
				login_nav = document.getElementById('login_nav');
				regi_nav = document.getElementById('regi_nav');
				
				login_nav.style.display = 'none';
				regi_nav.style.display = 'none';
			</script>
		</div>
	</div>
</div>

{% endblock %}

cps2/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="header">
              <h1 style="" class="text-center my-4">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
            </div>

			<div class="row d-flex justify-content-center" style="width: 30%;">

					<table class="table table-bordered table-condensed text-center">
						<thead style="background-color: black;color: white;font-size: 20px;">
							<tr>
								<th class="col-5">Tasks</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<!-- TASK -->
								{% if todoitem_list %}
									<td>
										{% for todoitem in todoitem_list %}
										<li class="list-group-item">
											<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
												{{ todoitem.task_name }}
											</a>
										</li>
										{% endfor %}
									</td>
								{% else %}
									<td>
										<p class="text-center my-3">No tasks have been created.</p>
									</td>
								{% endif %}
							</tr>
						</tbody>
					</table>

					<table class="table table-bordered table-condensed text-center">
						<thead style="background-color: black;color: white;font-size: 20px;">
							<tr>
								<th class="col-5">Events</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<!-- EVENT -->
								{% if todoevent %}
									<td>
										{% for events in todoevent %}
										<li class="list-group-item">
											<a href="{% url 'todolist:viewevent' events.id %}" class="text-decoration-none">
												{{ events.event_name }}
											</a>
										</li>
										{% endfor %}
									</td>
								{% else %}
									<td>
										<p class="my-2">No events have been created.</p>
									</td>
								{% endif %}
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			login_nav = document.getElementById('login_nav');
			regi_nav = document.getElementById('regi_nav');

			login_nav.style.display = 'none';
			regi_nav.style.display = 'none';
		</script>
	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		<script type="text/javascript">
			logout_nav = document.getElementById('logout_nav');
			add_nav = document.getElementById('add_nav');
			add_event = document.getElementById('add_event');

			add_event.style.display = 'none';
			logout_nav.style.display = 'none';
			add_nav.style.display = 'none';
		</script>
	{% endif %}
{% endblock %}

cps2/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
	{% if user.is_anonymous == True %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Login</h1>
					{% if error == True %}
						<p class="text-danger">Invalid user credentials, please check your username and password</p>
					{% endif %}
					<form action="{% url 'todolist:login' %}" method="post">
						{% csrf_token %}
						<div class="mb-3">
							<label for="username">Username: </label>
							<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
						</div>
						<div class="mb-3">
							<label for="password">Password: </label>
							<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
						</div>
						<div class="text-center d-grid gap-1">
							<input class="btn btn-success" type="submit" value="Login">
						</div>
					</form>
					<script type="text/javascript">
						logout_nav = document.getElementById('logout_nav');
						add_nav = document.getElementById('add_nav');
						add_event = document.getElementById('add_event');
			
						add_event.style.display = 'none';
						logout_nav.style.display = 'none';
						add_nav.style.display = 'none';
					</script>
				</div>
			</div>
		</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

cps2/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Join Us</h1>
			{% if error == True %}
				<h1 class="text-danger">Duplicated User Found</h1>
				<p class="text-danger">A Duplicate User has been Found! User Creation Unsuccessful</p>
			{% elif match == True %}
				<p class="text-danger">Password doesn't Match</p>
			{% endif %}
			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="username">Username: </label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>
				<div class="row">
					<div class="col-6">
						<div class="mb-3">
							<label for="first_name">First Name: </label>
							<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
						</div>
					</div>
					<div class="col-6">
						<div class="mb-3">
							<label for="last_name">Last Name: </label>
							<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
						</div>
					</div>
				</div>
				<div class="mb-3">
					<label for="email">Email: </label>
					<input class="form-control" id="email" type="email" name="email" value="{{ email }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="password">Password: </label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="con_password">Confirm Password: </label>
					<input class="form-control" id="con_password" type="password" name="con_password" value="{{ con_password }}" maxlength="20" required>
				</div>
				<div class="text-center d-grid gap-1">
					<input class="btn btn-success" type="submit" value="Register">
				</div>
			</form>
			<script type="text/javascript">
				logout_nav = document.getElementById('logout_nav');
				add_nav = document.getElementById('add_nav');
				add_event = document.getElementById('add_event');
			
				add_event.style.display = 'none';
				logout_nav.style.display = 'none';
				add_nav.style.display = 'none';
			</script>
		</div>
	</div>
</div>
{% endblock %}

cps2/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %} View Task {% endblock %}

{% block content %}

<div class="container my-5">
	<div class="row d-flex justify-content-center">
		<div class="col-5">
			<div class="mx-auto">
				<div class="card">
					<h1 class="card-header text-center" style="background-color: black;color: white;font-size: 40px;"> {{ task_name }} </h1>
					<div class="card-body">
						<h5 class="card-title text-center"><b>Status</b></h5>
						<h6 class="text-center">{{ status }} </h6>
						<p class="card-text text-center">Description: {{ description }}</p>
					</div>
					<div class="card-footer p-2 text-center">
						<div class="row">
							<div class="col-4 d-grid gap-1">
								<button class="btn btn-success mx-1 text-decoration-none">
									<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">
										Edit Task
									</a>
								</button>
							</div>
							<div class="col-4 d-grid gap-1">
								<button class="btn btn-warning mx-1 text-decoration-none">
									<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">
										Delete Task
									</a>
								</button>
							</div>
							<div class="col-4 d-grid gap-1">
								<button class="btn btn-danger mx-1 text-decoration-none">
									<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
										Back to Tasks
									</a>
								</button>
							</div>
						</div>						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	login_nav = document.getElementById('login_nav');
	regi_nav = document.getElementById('regi_nav');
	
	login_nav.style.display = 'none';
	regi_nav.style.display = 'none';
</script>

{% endblock %}

cps2/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

{% block title %} Update Profile {% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Profile</h1>
				<form action="{% url 'todolist:update_profile' user_id %}" method="post">
					{% csrf_token %}
					
					{% for field in form %}
						<div class="mb-3">
							<label for="first_name">{{ field.label_tag }}</label>
							{{ field }}
						</div>
					{% endfor %}
					
					<div class="text-center d-grid gap-1">
						<input class="btn btn-success" type="submit" value="Update Profile">
					</div>
				</form>
				<script type="text/javascript">
					login_nav = document.getElementById('login_nav');
					regi_nav = document.getElementById('regi_nav');

					login_nav.style.display = 'none';
					regi_nav.style.display = 'none';
				</script>
			</div>
		</div>
	</div>
	{% endif %}
{% endblock %}

cps2/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %} Update Task {% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="task_name">Task Name: </label>
						<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="description">Description: </label>
						<textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status: </label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center d-grid gap-1">
						<input class="btn btn-success" type="submit" value="Update Task">
					</div>
				</form>
			</div>
		</div>	
	</div>
	<script type="text/javascript">
		login_nav = document.getElementById('login_nav');
		regi_nav = document.getElementById('regi_nav');
		
		login_nav.style.display = 'none';
		regi_nav.style.display = 'none';
	</script>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login<a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

cps2/todolist/templates/todolist/view_event.html
{% extends 'base.html' %}

{% block title %} View Task {% endblock %}

{% block content %}

<div class="container my-5">
	<div class="row d-flex justify-content-center">
		<div class="col-5">
			<div class="mx-auto">
				<div class="card">
					<h1 class="card-header text-center" style="background-color: black;color: white;font-size: 40px;"> {{ event_name }} </h1>
					<div class="card-body">
						<h5 class="card-title text-center"><b>Status</b></h5>
						<h6 class="text-center">{{ status }} </h6>
						<p class="card-text text-center">Description: {{ description }}</p>
					</div>
					<div class="card-footer p-2 text-center">
						<div class="d-grid gap-5">
							<button class="btn btn-danger mx-1 text-decoration-none">
								<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
									Back to Tasks
								</a>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	login_nav = document.getElementById('login_nav');
	regi_nav = document.getElementById('regi_nav');
	
	login_nav.style.display = 'none';
	regi_nav.style.display = 'none';
</script>

{% endblock %}